// Returns the top N cities per US state for use as geographic search targets.

const CITIES_BY_STATE = {
  AL: ['Birmingham','Montgomery','Huntsville','Mobile','Tuscaloosa','Hoover','Dothan','Auburn','Decatur','Madison','Florence','Gadsden','Vestavia Hills','Prattville','Phenix City','Alabaster','Bessemer','Enterprise','Anniston','Daphne','Northport','Oxford','Troy','Pelham','Talladega','Opelika','Homewood','Athens','Albertville','Trussville'],
  AK: ['Anchorage','Fairbanks','Juneau','Sitka','Ketchikan','Wasilla','Kenai','Kodiak','Bethel','Palmer','Homer','Unalaska','Barrow','Soldotna','Valdez','Nome','Kotzebue','Seward','Cordova','Dillingham','Wrangell','Haines','Craig','Skagway','Metlakatla','Sand Point','King Cove','Akutan','Togiak','Quinhagak'],
  AZ: ['Phoenix','Tucson','Mesa','Chandler','Scottsdale','Glendale','Gilbert','Tempe','Peoria','Surprise','Yuma','Avondale','Goodyear','Flagstaff','Buckeye','Lake Havasu City','Casa Grande','Sierra Vista','Maricopa','Oro Valley','Prescott','Bullhead City','Prescott Valley','Apache Junction','Queen Creek','Kingman','San Luis','Sahuarita','Florence','El Mirage'],
  AR: ['Little Rock','Fort Smith','Fayetteville','Springdale','Jonesboro','Conway','Rogers','Pine Bluff','Bentonville','Hot Springs','Benton','Texarkana','Sherwood','Jacksonville','North Little Rock','Russellville','Bella Vista','West Memphis','Paragould','Cabot','Searcy','Van Buren','El Dorado','Maumelle','Bryant','Forrest City','Harrison','Mountain Home','Magnolia','Siloam Springs'],
  CA: ['Los Angeles','San Diego','San Jose','San Francisco','Fresno','Sacramento','Long Beach','Oakland','Bakersfield','Anaheim','Santa Ana','Riverside','Stockton','Chula Vista','Irvine','Fremont','San Bernardino','Modesto','Fontana','Moreno Valley','Oxnard','Glendale','Huntington Beach','Santa Clarita','Garden Grove','Oceanside','Rancho Cucamonga','Santa Rosa','Ontario','Elk Grove'],
  CO: ['Denver','Colorado Springs','Aurora','Fort Collins','Lakewood','Thornton','Arvada','Westminster','Pueblo','Centennial','Boulder','Highlands Ranch','Greeley','Longmont','Loveland','Broomfield','Castle Rock','Commerce City','Parker','Northglenn','Brighton','Littleton','Englewood','Wheat Ridge','Pueblo West','Falcon','Windsor','Erie','Canon City','Montrose'],
  CT: ['Bridgeport','New Haven','Hartford','Stamford','Waterbury','Norwalk','Danbury','New Britain','West Hartford','Greenwich','Hamden','Meriden','Bristol','Manchester','West Haven','Milford','Stratford','East Hartford','Middletown','Wallingford','Enfield','Southington','Shelton','Norwich','Torrington','Trumbull','Glastonbury','Naugatuck','Cheshire','Newington'],
  DE: ['Wilmington','Dover','Newark','Middletown','Smyrna','Milford','Seaford','Georgetown','Elsmere','New Castle','Bear','Glasgow','Edgemoor','Claymont','Pike Creek Valley','Hockessin','Brookside','Wilmington Manor','Long Neck','Laurel','Harrington','Camden','Lewes','Millsboro','Bridgeville','Selbyville','Millville','Ocean View','Bethany Beach','Felton'],
  FL: ['Jacksonville','Miami','Tampa','Orlando','St. Petersburg','Hialeah','Tallahassee','Fort Lauderdale','Port St. Lucie','Cape Coral','Pembroke Pines','Hollywood','Miramar','Gainesville','Coral Springs','Clearwater','Miami Gardens','Palm Bay','Pompano Beach','West Palm Beach','Lakeland','Davie','Miami Beach','Sunrise','Brandon','Spring Hill','Boca Raton','Deltona','Plantation','Alafaya'],
  GA: ['Atlanta','Augusta','Columbus','Macon','Savannah','Athens','Sandy Springs','Roswell','Johns Creek','Albany','Warner Robins','Alpharetta','Marietta','Valdosta','Smyrna','Brookhaven','Dunwoody','Peachtree City','Newnan','Rome','Milton','East Point','Gainesville','Hinesville','Peachtree Corners','Kennesaw','LaGrange','Dalton','Douglasville','Woodstock'],
  HI: ['Honolulu','East Honolulu','Pearl City','Hilo','Kailua','Waipahu','Kaneohe','Mililani Town','Kahului','Ewa Gentry','Mililani Mauka','Kihei','Makakilo','Wahiawa','Halawa','Wailuku','Ewa Beach','Kapolei','Aiea','Makaha','Waimalu','Waikele','Nanakuli','Lahaina','Kapaa','Kailua-Kona','Waianae','Pearl Harbor','Holualoa','Waipio'],
  ID: ['Boise','Meridian','Nampa','Idaho Falls','Pocatello','Caldwell','Coeur d\'Alene','Twin Falls','Lewiston','Post Falls','Rexburg','Eagle','Moscow','Kuna','Ammon','Chubbuck','Hayden','Blackfoot','Garden City','Mountain Home','Hailey','Jerome','Burley','Sandpoint','Middleton','Star','Rathdrum','Rupert','Fruitland','Emmett'],
  IL: ['Chicago','Aurora','Joliet','Rockford','Springfield','Elgin','Peoria','Champaign','Waukegan','Cicero','Bloomington','Evanston','Decatur','Palatine','Arlington Heights','Bolingbrook','Schaumburg','Naperville','Downers Grove','Wheaton','Orland Park','Oak Lawn','Des Plaines','Berwyn','Skokie','Tinley Park','Oak Park','Carpentersville','Gurnee','Hanover Park'],
  IN: ['Indianapolis','Fort Wayne','Evansville','South Bend','Carmel','Fishers','Bloomington','Hammond','Gary','Lafayette','Muncie','Terre Haute','Kokomo','Anderson','Columbus','Noblesville','Greenwood','Elkhart','Mishawaka','Lawrence','Jeffersonville','New Albany','Portage','Richmond','Westfield','Avon','Plainfield','Michigan City','Crown Point','Valparaiso'],
  IA: ['Des Moines','Cedar Rapids','Davenport','Sioux City','Iowa City','Waterloo','Ames','West Des Moines','Council Bluffs','Ankeny','Dubuque','Cedar Falls','Marion','Bettendorf','Urbandale','Waukee','Coralville','North Liberty','Johnston','Mason City','Marshalltown','Clinton','Burlington','Ottumwa','Fort Dodge','Muscatine','Clive','Newton','Iowa Falls','Oskaloosa'],
  KS: ['Wichita','Overland Park','Kansas City','Olathe','Topeka','Lawrence','Shawnee','Manhattan','Lenexa','Salina','Hutchinson','Leavenworth','Leawood','Dodge City','Garden City','Junction City','Emporia','Derby','Prairie Village','Liberal','Hays','Pittsburg','Newton','Gardner','Roeland Park','Merriam','Great Bend','El Dorado','Andover','Lansing'],
  KY: ['Louisville','Lexington','Bowling Green','Owensboro','Covington','Hopkinsville','Richmond','Florence','Georgetown','Henderson','Elizabethtown','Nicholasville','Independence','Jeffersontown','Paducah','Frankfort','Radcliff','Ashland','Madisonville','Murray','Erlanger','Shively','St. Matthews','Danville','Bardstown','Winchester','Burlington','Campbellsville','Lawrenceburg','Berea'],
  LA: ['New Orleans','Baton Rouge','Shreveport','Metairie','Lafayette','Lake Charles','Bossier City','Kenner','Monroe','Marrero','Alexandria','New Iberia','Laplace','Houma','Hammond','Prairieville','Harvey','Central','Slidell','Terrytown','Natchitoches','Sulphur','Thibodaux','Ruston','Pineville','Ponchatoula','Morgan City','Youngsville','Zachary','Covington'],
  ME: ['Portland','Lewiston','Bangor','South Portland','Auburn','Biddeford','Sanford','Saco','Augusta','Westbrook','Waterville','Brewer','Presque Isle','Bath','Caribou','Ellsworth','Old Town','Rockland','Belfast','Calais','Pittsfield','Houlton','Bar Harbor','Gardiner','Hallowell','Eastport','Millinocket','Dover-Foxcroft','Madison','Rumford'],
  MD: ['Baltimore','Columbia','Germantown','Silver Spring','Waldorf','Ellicott City','Glen Burnie','Dundalk','Rockville','Gaithersburg','Annapolis','Frederick','Bethesda','Towson','Bowie','Aspen Hill','Wheaton','Hagerstown','Potomac','Essex','Catonsville','Laurel','Bel Air','Cumberland','Salisbury','Greenbelt','Hyattsville','College Park','Bowie','Lexington Park'],
  MA: ['Boston','Worcester','Springfield','Lowell','Cambridge','New Bedford','Brockton','Quincy','Lynn','Fall River','Newton','Lawrence','Somerville','Waltham','Haverhill','Malden','Medford','Taunton','Chicopee','Weymouth','Revere','Peabody','Methuen','Barnstable','Pittsfield','Attleboro','Salem','Framingham','Plymouth','Westfield'],
  MI: ['Detroit','Grand Rapids','Warren','Sterling Heights','Lansing','Ann Arbor','Flint','Dearborn','Livonia','Westland','Troy','Farmington Hills','Kalamazoo','Wyoming','Rochester Hills','Southfield','Pontiac','Taylor','St. Clair Shores','Dearborn Heights','Royal Oak','Roseville','Saginaw','Jackson','Muskegon','Canton','East Lansing','Bloomfield Township','Novi','Sterling Heights'],
  MN: ['Minneapolis','Saint Paul','Rochester','Duluth','Bloomington','Brooklyn Park','Plymouth','St. Cloud','Eagan','Woodbury','Maple Grove','Coon Rapids','Burnsville','Eden Prairie','Blaine','Lakeville','Minnetonka','Apple Valley','Edina','St. Louis Park','Mankato','Maplewood','Moorhead','Shakopee','Richfield','Roseville','Savage','Fridley','Brooklyn Center','Oakdale'],
  MS: ['Jackson','Gulfport','Southaven','Hattiesburg','Biloxi','Meridian','Tupelo','Greenville','Olive Branch','Horn Lake','Clinton','Pearl','Ridgeland','Madison','Starkville','Columbus','Oxford','Vicksburg','Pascagoula','Laurel','Gautier','Ocean Springs','Hernando','Natchez','Long Beach','Corinth','Brandon','Clarksdale','Grenada','Flowood'],
  MO: ['Kansas City','St. Louis','Springfield','Columbia','Independence','Lee\'s Summit','O\'Fallon','St. Joseph','St. Charles','Blue Springs','Joplin','Chesterfield','Jefferson City','Cape Girardeau','Florissant','Hazelwood','Webster Groves','Raytown','University City','Ballwin','Kirkwood','Clayton','Gladstone','Grandview','Wildwood','Belton','Raymore','Wentzville','Arnold','Nixa'],
  MT: ['Billings','Missoula','Great Falls','Bozeman','Butte','Helena','Kalispell','Havre','Anaconda','Miles City','Belgrade','Livingston','Laurel','Whitefish','Lewistown','Sidney','Glendive','Columbia Falls','Polson','Hamilton','Hardin','Dillon','Glasgow','Wolf Point','Malta','Chinook','Deer Lodge','Thompson Falls','Red Lodge','Libby'],
  NE: ['Omaha','Lincoln','Bellevue','Grand Island','Kearney','Fremont','Hastings','Norfolk','Columbus','Papillion','La Vista','Lexington','Scottsbluff','North Platte','South Sioux City','Beatrice','Blair','Gering','York','Crete','Nebraska City','Seward','McCook','Alliance','Holdrege','O\'Neill','Plattsmouth','Aurora','Schuyler','Wahoo'],
  NV: ['Las Vegas','Henderson','Reno','North Las Vegas','Sparks','Carson City','Fernley','Elko','Mesquite','Boulder City','Fallon','Winnemucca','West Wendover','Ely','Yerington','Lovelock','Wells','Carlin','Hawthorne','Tonopah','Battle Mountain','Pahrump','Enterprise','Spring Valley','Summerlin South','Whitney','Paradise','Sunrise Manor','Winchester','Nellis AFB'],
  NH: ['Manchester','Nashua','Concord','Derry','Dover','Rochester','Salem','Merrimack','Hudson','Londonderry','Keene','Bedford','Portsmouth','Goffstown','Laconia','Hampton','Milford','Durham','Exeter','Windham','Pelham','Hooksett','Claremont','Lebanon','Berlin','Somersworth','Hanover','Amherst','Raymond','Conway'],
  NJ: ['Newark','Jersey City','Paterson','Elizabeth','Edison','Woodbridge','Lakewood','Toms River','Hamilton','Trenton','Clifton','Camden','Brick','Cherry Hill','Passaic','Middletown','Union City','Old Bridge','Gloucester Township','Hackensack','Bayonne','East Orange','North Bergen','Piscataway','West New York','Vineland','New Brunswick','Perth Amboy','Jackson','Wayne'],
  NM: ['Albuquerque','Las Cruces','Rio Rancho','Santa Fe','Roswell','Farmington','Clovis','Hobbs','Alamogordo','Carlsbad','Gallup','Artesia','Lovington','Portales','Los Lunas','Espanola','Sunland Park','Silver City','Los Alamos','Taos','Anthony','Bernalillo','Aztec','Deming','Ruidoso','Socorro','Truth or Consequences','Tucumcari','Grants','Belen'],
  NY: ['New York City','Buffalo','Rochester','Yonkers','Syracuse','Albany','New Rochelle','Mount Vernon','Schenectady','Utica','White Plains','Hempstead','Troy','Niagara Falls','Binghamton','Freeport','Valley Stream','Long Beach','Spring Valley','Rome','Ithaca','North Hempstead','Ramapo','Huntington','Amherst','Greece','Irondequoit','Tonawanda','Cheektowaga','Brookhaven'],
  NC: ['Charlotte','Raleigh','Greensboro','Durham','Winston-Salem','Fayetteville','Cary','Wilmington','High Point','Concord','Asheville','Gastonia','Jacksonville','Chapel Hill','Huntersville','Apex','Rocky Mount','Greenville','Burlington','Kannapolis','Wilson','Mooresville','Monroe','Sanford','Matthews','New Bern','Goldsboro','Indian Trail','Morganton','Kernersville'],
  ND: ['Fargo','Bismarck','Grand Forks','Minot','West Fargo','Williston','Dickinson','Mandan','Jamestown','Wahpeton','Devils Lake','Valley City','Grafton','Bottineau','Rugby','Mayville','Carrington','Lisbon','New Rockford','Stanley','Beulah','Watford City','Lincoln','Casselton','Horace','Hazen','Northwood','Harvey','Langdon','Crosby'],
  OH: ['Columbus','Cleveland','Cincinnati','Toledo','Akron','Dayton','Parma','Canton','Youngstown','Lorain','Hamilton','Springfield','Kettering','Elyria','Lakewood','Newark','Cuyahoga Falls','Dublin','Middletown','Beavercreek','Cleveland Heights','Mentor','Euclid','Fairfield','Mansfield','Strongsville','Massillon','Warren','Troy','Hilliard'],
  OK: ['Oklahoma City','Tulsa','Norman','Broken Arrow','Lawton','Edmond','Moore','Midwest City','Enid','Stillwater','Muskogee','Bartlesville','Owasso','Shawnee','Yukon','Ardmore','Ponca City','Bixby','Duncan','Del City','Jenks','Sand Springs','Sapulpa','Altus','Claremore','McAlester','Tahlequah','El Reno','Ada','Durant'],
  OR: ['Portland','Salem','Eugene','Gresham','Hillsboro','Beaverton','Bend','Medford','Springfield','Corvallis','Albany','Tigard','Lake Oswego','Ashland','Aloha','Grants Pass','Oregon City','McMinnville','Tualatin','Redmond','Coos Bay','Pendleton','Roseburg','Newberg','Klamath Falls','West Linn','Woodburn','Forest Grove','Keizer','Wilsonville'],
  PA: ['Philadelphia','Pittsburgh','Allentown','Erie','Reading','Scranton','Bethlehem','Lancaster','Harrisburg','Altoona','York','State College','Wilkes-Barre','Chester','Norristown','Easton','Lebanon','Hazleton','New Castle','Johnstown','Williamsport','Monroeville','McKeesport','Pottsville','Chambersburg','Sharon','Bloomsburg','Carlisle','Lower Merion','Bethel Park'],
  RI: ['Providence','Cranston','Warwick','Pawtucket','East Providence','Woonsocket','Coventry','Cumberland','North Providence','South Kingstown','West Warwick','Johnston','North Kingstown','Newport','Bristol','Westerly','Smithfield','Lincoln','Burrillville','Middletown','Tiverton','East Greenwich','Barrington','North Smithfield','Warren','Scituate','Glocester','Hopkinton','Exeter','West Greenwich'],
  SC: ['Columbia','Charleston','North Charleston','Mount Pleasant','Rock Hill','Greenville','Summerville','Goose Creek','Hilton Head Island','Sumter','Florence','Spartanburg','Myrtle Beach','Mauldin','Simpsonville','Aiken','Anderson','Greer','North Augusta','Conway','Beaufort','Bluffton','Lexington','Easley','Irmo','Hanahan','Five Forks','Greenwood','Cayce','Socastee'],
  SD: ['Sioux Falls','Rapid City','Aberdeen','Brookings','Watertown','Mitchell','Yankton','Pierre','Huron','Spearfish','Vermillion','Brandon','Box Elder','Sturgis','Harrisburg','Madison','Belle Fourche','Tea','Hot Springs','Lead','Mobridge','Milbank','Winner','Chamberlain','Sisseton','Beresford','Canton','Dell Rapids','Elk Point','Lennox'],
  TN: ['Memphis','Nashville','Knoxville','Chattanooga','Clarksville','Murfreesboro','Franklin','Jackson','Johnson City','Bartlett','Hendersonville','Kingsport','Collierville','Cleveland','Smyrna','Germantown','Brentwood','Columbia','Spring Hill','La Vergne','Cookeville','Mount Juliet','Morristown','Oak Ridge','Shelbyville','Maryville','Bristol','Lebanon','Gallatin','Farragut'],
  TX: ['Houston','San Antonio','Dallas','Austin','Fort Worth','El Paso','Arlington','Corpus Christi','Plano','Laredo','Lubbock','Garland','Irving','Amarillo','Grand Prairie','Brownsville','McKinney','Frisco','Pasadena','Killeen','McAllen','Mesquite','Denton','Carrollton','Midland','Waco','Round Rock','Abilene','Beaumont','Odessa'],
  UT: ['Salt Lake City','West Valley City','Provo','West Jordan','Orem','Sandy','Ogden','St. George','Layton','South Jordan','Millcreek','Taylorsville','Logan','Murray','Draper','Bountiful','Lehi','Riverton','Herriman','Spanish Fork','Roy','Pleasant Grove','Kearns','Tooele','Cottonwood Heights','Springville','Cedar City','Clearfield','American Fork','Kaysville'],
  VT: ['Burlington','Essex Junction','South Burlington','Colchester','Rutland','Bennington','Brattleboro','Milton','Williston','Montpelier','Winooski','Barre','Middlebury','Hartford','Springfield','Newport','Northfield','Morrisville','Johnson','Swanton','Vergennes','Shelburne','St. Johnsbury','Hyde Park','Derby','Randolph','Brandon','Lyndon','Manchester','Waterbury'],
  VA: ['Virginia Beach','Norfolk','Chesapeake','Arlington','Richmond','Newport News','Alexandria','Hampton','Roanoke','Portsmouth','Suffolk','Lynchburg','Harrisonburg','Leesburg','Charlottesville','Danville','Manassas','Petersburg','Fredericksburg','Winchester','Salem','Herndon','Reston','Tuckahoe','Dale City','Centreville','Lake Ridge','McLean','Ashburn','Annandale'],
  WA: ['Seattle','Spokane','Tacoma','Vancouver','Bellevue','Kent','Everett','Renton','Spokane Valley','Kirkland','Bellingham','Kennewick','Federal Way','Yakima','Redmond','Marysville','Pasco','Shoreline','Richland','Sammamish','Burien','Lacey','Lakewood','Edmonds','Bremerton','Puyallup','Olympia','Longview','Bothell','Auburn'],
  WV: ['Charleston','Huntington','Morgantown','Parkersburg','Wheeling','Weirton','Fairmont','Martinsburg','Beckley','Clarksburg','South Charleston','St. Albans','Vienna','Bluefield','Moundsville','Bridgeport','Oak Hill','Dunbar','Elkins','Nitro','Hurricane','Princeton','Lewisburg','Point Pleasant','Buckhannon','New Martinsville','Grafton','Summersville','Keyser','Williamson'],
  WI: ['Milwaukee','Madison','Green Bay','Kenosha','Racine','Appleton','Waukesha','Oshkosh','Eau Claire','Janesville','West Allis','La Crosse','Sheboygan','Wauwatosa','Fond du Lac','New Berlin','Wausau','Brookfield','Beloit','Greenfield','Franklin','Oak Creek','Fitchburg','Sun Prairie','Manitowoc','West Bend','Menomonee Falls','Neenah','Caledonia','Mequon'],
  WY: ['Cheyenne','Casper','Laramie','Gillette','Rock Springs','Sheridan','Green River','Evanston','Riverton','Jackson','Cody','Rawlins','Lander','Torrington','Powell','Douglas','Worland','Buffalo','Wheatland','Thermopolis','Newcastle','Glenrock','Lovell','Afton','Guernsey','Lyman','Dubois','Pinedale','Kemmerer','Greybull'],
};

function getCitiesByState(stateCode, limit) {
  const cities = CITIES_BY_STATE[stateCode.toUpperCase()];
  if (!cities) return [];
  return limit ? cities.slice(0, limit) : cities;
}

module.exports = { getCitiesByState, CITIES_BY_STATE };
